Update classes-wind-degrees.scss
Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: compound selectors may no longer be extended.
Consider `@extend .wi-wind, .towards-0-deg` instead.
See http://bit.ly/ExtendCompound for details.

    ╷
727 │   @extend .wi-wind.towards-0-deg;
    │           ^^^^^^^^^^^^^^^^^^^^^^
    ╵
  node_modules/weathericons/sass/icon-classes/classes-wind-degrees.scss 727:11  root stylesheet